[versions]
agp = "8.2.2"
converterGson = "2.9.0"
core = "3.4.1"
desugar_jdk_libs = "2.1.4"
dom4j = "1.6.1"
firebaseBom = "32.7.2"
firebaseUiAuth = "8.0.0"
googleWebrtc = "1.0.43591"
javaWebsocketVersion = "1.5.3"
journeyappsZxingAndroidEmbedded = "4.3.0"
kotlin = "1.9.21"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
kotlinStdlib = "1.9.21"
lifecycleViewmodelKtx = "2.7.0"
material = "1.11.0"
constraintlayout = "2.1.4"
mpandroidchart = "v3.1.0"
multidex = "2.0.1"
navigationFragmentKtx = "2.7.7"
navigationUiKtx = "2.7.7"
activity = "1.8.2"
firebaseAuthKtx = "22.3.1"
firebaseFirestoreKtx = "24.10.2"
gridlayout = "1.0.0"
playServicesLocation = "21.1.0"
programAb = "0.0.4"
roomCompiler = "2.6.1"
roomCompilerVersion = "2.6.1"
roomRuntime = "2.6.1"
slf4jAndroid = "1.7.36"
squareupRetrofit = "2.9.0"
roomCommon = "2.6.1"
roomKtx = "2.6.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
com-journeyapps-zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "journeyappsZxingAndroidEmbedded" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core = { module = "com.google.zxing:core", version.ref = "core" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
dom4j = { module = "dom4j:dom4j", version.ref = "dom4j" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
google-webrtc = { module = "com.infobip:google-webrtc", version.ref = "googleWebrtc" }
java-websocket-java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocketVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
program-ab = { module = "org.program-ab:program-ab", version.ref = "programAb" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareupRetrofit" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

